application: phaser
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /game1
  static_dir: game1
- url: /.*
  script: phaser.app

libraries:
- name: webapp2
  version: "2.5.2"
